version: "3.7"
services:
  web:
    build: .
    container_name: gitlab_rebuilt
    restart: on-failure
    hostname: 'gitlab.example.com:9090'
    # environment:
      # GITLAB_OMNIBUS_CONFIG: external_url "https://gitlab.example.com:"
      #  Add any other gitlab.rb configuration here, each on its own line
    ports:
      - "9090:9090"
      - '443:443'
      - '22:22'
    volumes:
      - "/Users/kuhlenkondeshe/srv/gitlab/config:/etc/gitlab:rw"
      - "/Users/kuhlenkondeshe/srv/gitlab/logs:/var/log/gitlab:rw"
      - "/Users/kuhlenkondeshe/srv/gitlab/data:/var/opt/gitlab:rw"

  jenkins:
    image: "jenkins/jenkins:lts"
    container_name: jenkins
    restart: on-failure
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home: